### ISSUE TITLE
Bug with multiple duplicate Legend Control

### ISSUE THREAD

**Issue by kingstakh** [yohanboniface/Leaflet.TileLegend#1]
Hi!
After collapse Legend Control adding multiple controls in attribution area and after dublicate all controls more and more. It's happend in your demo and in local.

**Comment by yohanboniface** [comment]
thanks for the report, I will have a look :)

**Comment by kingstakh** [comment]
It would be nice to fix it

**Comment by yohanboniface** [comment]
Humm, can you be a little bit more detailed in how to reproduce the problem? I'm testing in http://hotosm.github.io/HDM-CartoCSS/#13/19.6583/-72.1266 but can't see any problem.
Thanks!

**Comment by yohanboniface** [comment]
Also, what are your OS and browser versions?

**Comment by rntdrts** [comment]
it's not the OS or the browser, is the event's on 'layeradd' and on 'layerRemove' there's no diference for leafletjs, so it will check every single time you add a layer (popup, or a marker, or a line, ... etc) and your handling both the events in the wrong way.

**Comment by yohanboniface** [comment]
OK, now I've seen and reproduced the bug. Just pushing a fix.

**Comment by yohanboniface** [comment]
Seems good, thanks for the report amigos, and sorry for not having understood the problem quickly!

**Comment by rntdrts** [comment]
Great! I have been working with your plugin but i had already made a lot of changes, your solution works but try to think of it, using a baseLayer, there's where i think the plugin can gain some great features. (and i'm sorry if i'm writing on the wrong place, i don't know alot about the politics of github)
